# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import asr_pb2 as proto_dot_asr__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/asr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranscribe = channel.stream_stream(
                '/asr_concurrent_stream.ASRService/StreamTranscribe',
                request_serializer=proto_dot_asr__pb2.AudioChunkRequest.SerializeToString,
                response_deserializer=proto_dot_asr__pb2.TranscriptionResponse.FromString,
                _registered_method=True)
        self.StartStream = channel.unary_unary(
                '/asr_concurrent_stream.ASRService/StartStream',
                request_serializer=proto_dot_asr__pb2.StreamStartRequest.SerializeToString,
                response_deserializer=proto_dot_asr__pb2.StreamStartResponse.FromString,
                _registered_method=True)
        self.FinalizeStream = channel.unary_unary(
                '/asr_concurrent_stream.ASRService/FinalizeStream',
                request_serializer=proto_dot_asr__pb2.StreamFinalizeRequest.SerializeToString,
                response_deserializer=proto_dot_asr__pb2.StreamFinalizeResponse.FromString,
                _registered_method=True)
        self.GetStreamStatus = channel.unary_unary(
                '/asr_concurrent_stream.ASRService/GetStreamStatus',
                request_serializer=proto_dot_asr__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=proto_dot_asr__pb2.StreamStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/asr_concurrent_stream.ASRService/HealthCheck',
                request_serializer=proto_dot_asr__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_asr__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ASRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=proto_dot_asr__pb2.AudioChunkRequest.FromString,
                    response_serializer=proto_dot_asr__pb2.TranscriptionResponse.SerializeToString,
            ),
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=proto_dot_asr__pb2.StreamStartRequest.FromString,
                    response_serializer=proto_dot_asr__pb2.StreamStartResponse.SerializeToString,
            ),
            'FinalizeStream': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeStream,
                    request_deserializer=proto_dot_asr__pb2.StreamFinalizeRequest.FromString,
                    response_serializer=proto_dot_asr__pb2.StreamFinalizeResponse.SerializeToString,
            ),
            'GetStreamStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamStatus,
                    request_deserializer=proto_dot_asr__pb2.StreamStatusRequest.FromString,
                    response_serializer=proto_dot_asr__pb2.StreamStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_asr__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_asr__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asr_concurrent_stream.ASRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asr_concurrent_stream.ASRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/asr_concurrent_stream.ASRService/StreamTranscribe',
            proto_dot_asr__pb2.AudioChunkRequest.SerializeToString,
            proto_dot_asr__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr_concurrent_stream.ASRService/StartStream',
            proto_dot_asr__pb2.StreamStartRequest.SerializeToString,
            proto_dot_asr__pb2.StreamStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr_concurrent_stream.ASRService/FinalizeStream',
            proto_dot_asr__pb2.StreamFinalizeRequest.SerializeToString,
            proto_dot_asr__pb2.StreamFinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr_concurrent_stream.ASRService/GetStreamStatus',
            proto_dot_asr__pb2.StreamStatusRequest.SerializeToString,
            proto_dot_asr__pb2.StreamStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr_concurrent_stream.ASRService/HealthCheck',
            proto_dot_asr__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_asr__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
